In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.pylab as pylab
import pybrain

importing FeedForward Network class from pybrain

In [2]:
from pybrain import FeedForwardNetwork
n = FeedForwardNetwork()

importing LinearLayer and SigmoidLayer as layer class of neurons for each layer

In [3]:
from pybrain import LinearLayer,SigmoidLayer
inLayer = LinearLayer(2)
hiddenLayer = SigmoidLayer(2)
outLayer = LinearLayer(1)

Adding layers to FFN

In [4]:
n.addInputModule(inLayer)
n.addModule(hiddenLayer)
n.addOutputModule(outLayer)

Import FullConnecition Class to create matrix for connections between layers

In [5]:
from pybrain import FullConnection
in_to_hidden = FullConnection(inLayer,hiddenLayer)
hidden_to_out = FullConnection(hiddenLayer,outLayer)

Add connections to FNN

In [6]:
n.addConnection(in_to_hidden)
n.addConnection(hidden_to_out)

Sort Modules in FNN for initialice the FNN as topologically sorted of the modules (layers)

In [7]:
n.sortModules()

Printing the FNN estructures 

In [8]:
print n

FeedForwardNetwork-6
   Modules:
    [<LinearLayer 'LinearLayer-3'>, <SigmoidLayer 'SigmoidLayer-7'>, <LinearLayer 'LinearLayer-8'>]
   Connections:
    [<FullConnection 'FullConnection-4': 'SigmoidLayer-7' -> 'LinearLayer-8'>, <FullConnection 'FullConnection-5': 'LinearLayer-3' -> 'SigmoidLayer-7'>]



activating the FFN

In [9]:
n.activate([1,2])

array([-1.38922383])

Checking connections weigths

In [10]:
in_to_hidden.params

array([ 0.78400177,  0.72852973, -0.27533457,  1.11515738])

In [11]:
hidden_to_out.params

array([-0.56228732, -1.00570414])

In [12]:
n.params

array([ 0.78400177,  0.72852973, -0.27533457,  1.11515738, -0.56228732,
       -1.00570414])